apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hooks-cert-mypraxos
  namespace: hetairoi
spec:
  commonName: hooks.mypraxos.com
  dnsNames:
  - hooks.mypraxos.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-http01
  secretName: hooks-mypraxos-tls
