apiVersion: v1
kind: Service
metadata:
  name: hetairoi-web-service
  namespace: hetairoi
spec:
  selector:
    app: hetairoi-web # This selector correctly matches your hetairoi-web-deployment
  ports:
    - protocol: TCP
      port: 443 # Service port (internal cluster traffic)
      targetPort: 8000 # Pod port
  type: ClusterIP