apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: hetairoi

images:
  - name: praxosagentcontainers.azurecr.io/hetairoi-worker
    digest: sha256:36e9aad8a62a24170a5f91d2434f7cb19df5d6e7d62665742debdeb77e9f37b4