apiVersion: v1
kind: Service
metadata:
  name: hetairoi-worker-service
spec:
  selector:
    app: hetairoi-worker
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8000
  type: ClusterIP
